function [fitresult, gof] = createFit(topo2, chloro2)
%CREATEFIT(TOPO2,CHLORO2)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: topo2
%      Y Output: chloro2
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 31-Oct-2023 17:48:50


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( topo2, chloro2 );

% Set up fittype and options.
ft = fittype( 'exp2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [1.47964539763171e-06 -0.00199496747443956 0.364443275327515 0.000106836988614046];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'chloro2 vs. topo2', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'topo2', 'Interpreter', 'none' );
ylabel( 'chloro2', 'Interpreter', 'none' );
grid on


